name: integrations tests
on: [push]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node 16.13.2
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      - name: Cypress integration tests
        uses: cypress-io/github-action@v4.1.0
        with:
          install: false
          # working-directory: packages/e2e
          start: yarn start-server
